### PR TITLE
Added my fork to the extensions

### PR DESCRIPTION
**Pull request by Raiondesu**
As discussed. ^_^

### CODE REVIEW

**Comment by troxler** [comment]
@Raiondesu FYI: Still waiting on an answer to [this](https://github.com/troxler/vue-headful/pull/2#issuecomment-377889421) and an update of your readme.

**Comment by Raiondesu** [comment]
@troxler, what exactly do you mean by "an update" on my readme?

**Comment by troxler** [comment]
The [readme](https://github.com/VeryWow/vue-simple-headful/blob/master/readme.md) still mentions "vue-headful" when it clearly should be "vue-simple-headful". For example in `npm i -S vue-headful`.

**Comment by troxler** [comment]
Closing due to inactivity.

**Pull request closed without merging**
