### PR TITLE
Added some properties for image

### PR DESCRIPTION
**Pull request by kaskar2008**
In some cases properties "og:image:secure_url" and "thumbnailUrl" are also mandatory.

### CODE REVIEW

**Comment by kaskar2008** [comment]
@troxler I need this in your lib, pls :)

**Comment by kaskar2008** [comment]
@troxler ??

**Comment by troxler** [comment]
@kaskar2008 I will look at it as soon as possible. Until then, you could use the `head` property.

**Comment by troxler** [comment]
Do you have a usecase or a reference describing when you should use

* `property="og:image"` and `property="og:image:secure_url"` with the *same* URL? As far as I understand from the documentation, the latter only has to be specified when the former is not an HTTPS URL. So setting both to the same HTTPS URL seems useless.
* `itemprop="image"` and `itemprop="thumbnailUrl"` with the *same* URL? They seem to have different semantics and setting both to the same URL seems overkill. Do you know any service that only reads `itemprop="thumbnailUrl"` and ignores `itemprop="image"`?

**Comment by troxler** [comment]
Closing due to inactivity.

**Pull request closed without merging**
